####################################################################################################
# Copyright (c) 2023 Bahman Movaqar
#
# This file is part of lemmy-meter.
# lemmy-meter is free software: you can redistribute it and/or modify it under the terms of the GNU
# General Public License as published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version.
#
# lemmy-meter is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without
# even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
# General Public License for more details.
#
# You should have received a copy of the GNU General Public License along with lemmy-meter.
# If not, see <https://www.gnu.org/licenses/>.
####################################################################################################

---
groups:
  - name: Unavailable
    rules:
      - alert: WARN - Instance Unavailable
        expr: lemmy_instance:failed:probe_success:count == 4
        for: 5m
        labels:
          severity: warning
          lemmy_instance: "{{ $labels.lemmy_instance }}"
          category: instance_unavailable
        annotations:
          summary: "[Unavailable] [5+ mins] {{ $labels.lemmy_instance }}"
          description: "«{{ $labels.lemmy_instance }}» has been unavailable for more than «5» minutes."

      - alert: ERROR - Instance Unavailable
        expr: lemmy_instance:failed:probe_success:count == 4
        for: 10m
        labels:
          severity: error
          lemmy_instance: "{{ $labels.lemmy_instance }}"
          category: instance_unavailable
        annotations:
          summary: "[Unavailable] [10+ mins] {{ $labels.lemmy_instance }}"
          description: "«{{ $labels.lemmy_instance }}» has been unavailable for more than «10» minutes."

  - name: Low Availability
    rules:
      - alert: WARN - Availability
        expr: lemmy_instance:availability:1h:percent < 70
        for: 15m
        labels:
          severity: warning
          lemmy_instance: "{{ $labels.lemmy_instance }}"
          category: instance_availability
        annotations:
          summary: "[Availability < 70%] [15+ mins] {{ $labels.lemmy_instance }}"
          description: "«{{ $labels.lemmy_instance }}» availability has been below 70% for more than 15 minutes."

      - alert: ERROR - Low Availability
        expr: lemmy_instance:availability:1h:percent < 70
        for: 30m
        labels:
          severity: error
          lemmy_instance: "{{ $labels.lemmy_instance }}"
          category: instance_availability
        annotations:
          summary: "[Availability < 70%] [30+ mins] {{ $labels.lemmy_instance }}"
          description: "«{{ $labels.lemmy_instance }}» availability has been below 70% for more than 30 minutes."

  - name: High Latency
    rules:
      - alert: WARN - Latency
        expr: lemmy_instance:relative_latency:1h:7d:percent > 30
        for: 15m
        labels:
          severity: warning
          lemmy_instance: "{{ $labels.lemmy_instance }}"
          category: instance_latency
        annotations:
          summary: "[Latency spike > 30%] [15+ mins] {{ $labels.lemmy_instance }}"
          description: "«{{ $labels.lemmy_instance }}» latency has been increasing by at least 30% for more than 15 minutes."

      - alert: ERROR - Latency
        expr: lemmy_instance:relative_latency:1h:7d:percent > 30
        for: 15m
        labels:
          severity: error
          lemmy_instance: "{{ $labels.lemmy_instance }}"
          category: instance_latency
        annotations:
          summary: "[Latency spike > 30%] [30+ mins] {{ $labels.lemmy_instance }}"
          description: "«{{ $labels.lemmy_instance }}» latency has been increasing by at least 30% for more than 30 minutes."
