---
modules:
  default:
    metrics:
      - name: scheduled_downtime
        type: object
        path: "{ .scheduled_downtime[*] }"
        help: Scheduled downtime indicator
        labels:
          lemmy_instance: "{ .lemmy_instance }"
        values:
          indicator: 100
