####################################################################################################
# Copyright (c) 2023 Bahman Movaqar
#
# This file is part of lemmy-meter.
# lemmy-meter is free software: you can redistribute it and/or modify it under the terms of the GNU
# General Public License as published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version.
#
# lemmy-meter is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without
# even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
# General Public License for more details.
#
# You should have received a copy of the GNU General Public License along with lemmy-meter.
# If not, see <https://www.gnu.org/licenses/>.
####################################################################################################

---
####################################################################################################
# jobs
####################################################################################################

global:
  scrape_interval: 1m
  scrape_timeout: 57s
  evaluation_interval: 1m

scrape_configs:
  ##################################################################################################

  - job_name: api_getPosts
    scrape_interval: 1m
    metrics_path: /probe
    file_sd_configs:
      - refresh_interval: 10m
        files:
          - /etc/prometheus/blackbox-probe.d/http_api_2xx.yml
    relabel_configs:
      - source_labels: [__address__]
        target_label: lemmy_instance
      - source_labels: [__address__]
        target_label: __param_target
        replacement: https://$1/api/v3/post/list?limit=1
      - target_label: __address__
        replacement: blackbox_exporter:9115
      - source_labels: [probe]
        target_label: __param_module

  ##################################################################################################

  - job_name: api_getComments
    scrape_interval: 1m
    metrics_path: /probe
    file_sd_configs:
      - refresh_interval: 10m
        files:
          - /etc/prometheus/blackbox-probe.d/http_api_2xx.yml
    relabel_configs:
      - source_labels: [__address__]
        target_label: lemmy_instance
        replacement: $1
      - source_labels: [__address__]
        target_label: __param_target
        replacement: https://$1/api/v3/comment/list?limit=1
      - target_label: __address__
        replacement: blackbox_exporter:9115
      - source_labels: [probe]
        target_label: __param_module

  ##################################################################################################

  - job_name: api_getCommunities
    scrape_interval: 1m
    metrics_path: /probe
    file_sd_configs:
      - refresh_interval: 10m
        files:
          - /etc/prometheus/blackbox-probe.d/http_api_2xx.yml
    relabel_configs:
      - source_labels: [__address__]
        target_label: lemmy_instance
        replacement: $1
      - source_labels: [__address__]
        target_label: __param_target
        replacement: https://$1/api/v3/community/list?limit=1
      - target_label: __address__
        replacement: blackbox_exporter:9115
      - source_labels: [probe]
        target_label: __param_module

  ##################################################################################################

  - job_name: webpage_landing_page
    scrape_interval: 1m
    metrics_path: /probe
    file_sd_configs:
      - refresh_interval: 10m
        files:
          - /etc/prometheus/blackbox-probe.d/http_page_2xx.yml
    relabel_configs:
      - source_labels: [__address__]
        target_label: lemmy_instance
        replacement: $1
      - source_labels: [__address__]
        target_label: __param_target
        replacement: https://$1/
      - target_label: __address__
        replacement: blackbox_exporter:9115
      - source_labels: [probe]
        target_label: __param_module

  ##################################################################################################

  - job_name: planned_downtime_in_progress
    scrape_interval: 1m
    metrics_path: /probe
    params:
      module:
        - default
    static_configs:
      - targets:
          - http://planned_downtime:6060/planned-downtime-in-progress.json
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - target_label: __address__
        replacement: json_exporter:7979

  ##################################################################################################

  - job_name: node_stats
    metrics_path: /metrics
    static_configs:
      - targets:
          - blackbox_exporter:9115
          - planned_downtime:6060
          - json_exporter:7979
          - grafana:3000
          - prometheus:9090
