version: '3.8'

services:
  prometheus:
    image: prom/prometheus:v2.47.0
    volumes:
      - ./volumes/prometheus:/prometheus
    ports:
      - '9090:9090'
    user: '${UID}:${GID}'
    restart: always

  grafana:
    image: grafana/grafana:9.4.14
    ports:
      - '3000:3000'
    restart: always
