####################################################################################################
# Copyright (c) 2023 Bahman Movaqar
#
# This file is part of lemmy-meter.
# lemmy-meter is free software: you can redistribute it and/or modify it under the terms of the GNU
# General Public License as published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version.
#
# lemmy-meter is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without
# even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
# General Public License for more details.
#
# You should have received a copy of the GNU General Public License along with lemmy-meter.
# If not, see <https://www.gnu.org/licenses/>.
####################################################################################################

---
version: "3.8"
services:
  prometheus:
    image: "prom/prometheus:v2.47.0"
    command:
      - "--storage.tsdb.path=/prometheus"
      - "--storage.tsdb.retention.time=60d"
      - "--config.file=/etc/prometheus/prometheus.yml"
    ports:
      - "9090:9090"
    volumes:
      - "${CLUSTER_DEPLOY_ROOT}/prometheus:/etc/prometheus"
      - "prometheus-data:/prometheus"
    restart: always
  grafana:
    image: "grafana/grafana:9.4.14"
    volumes:
      - "${CLUSTER_DEPLOY_ROOT}/grafana/grafana.ini:/etc/grafana/grafana.ini"
      - "${CLUSTER_DEPLOY_ROOT}/grafana/grafana.db:/var/lib/grafana/grafana.db"
    ports:
      - "3000:3000"
    user: "${UID}:${GID}"
    restart: always
  blackbox-exporter:
    image: "prom/blackbox-exporter:v0.24.0"
    volumes:
      - "${CLUSTER_DEPLOY_ROOT}/blackbox-exporter/config.yml:/etc/blackbox_exporter/config.yml"
    ports:
      - "9115:9115"
    user: "${UID}:${GID}"
    restart: always
  json-exporter:
    image: "prometheuscommunity/json-exporter:v0.6.0"
    volumes:
      - "${CLUSTER_DEPLOY_ROOT}/json-exporter/config.yml:/etc/json_exporter-config.yml"
    command:
      - "--config.file=/etc/json_exporter-config.yml"
    ports:
      - "7979:7979"
    user: "${UID}:${GID}"
    restart: always
  downtime-processor:
    image: "bahmanm/lemmy-meter.downtime-processor:3a7b7bc"
    entrypoint:
      - "/opt/downtime-processor/downtime-processor.pl"
    command:
      - "prefork"
      - "-m"
      - "${LMDP_MODE}"
      - "-l"
      - "http://*:6060"
    ports:
      - "6060:6060"
    volumes:
      - "${CLUSTER_DEPLOY_ROOT}/downtime-processor/:/opt/downtime-processor"
    working_dir: "/opt/downtime-processor"
    environment:
      - LMDP_JSON_SCHEMA=/opt/downtime-processor/scheduled-downtime-schema.json
      - LMDP_SCRAPE_TARGETS=/opt/downtime-processor/scrape-targets.txt
      - LMDP_LOG_LEVEL=${LMDP_LOG_LEVEL}
      - LMDP_GSHEET_URL=${LMDP_GSHEET_URL}
      - LMDP_GSHEET_HEADER_ROWS=${LMDP_GSHEET_HEADER_ROWS}
    user: "${UID}:${GID}"
    restart: always
  matrix-webhook:
    image: nim65s/matrix-webhook:v3.8.0
    ports:
      - "4785:4785"
    environment:
      - HOST=0.0.0.0
      - PORT=4785
      - MATRIX_ID=${MATRIX_WEBHOOK_MATRIX_ID}
      - MATRIX_PW=${MATRIX_WEBHOOK_MATRIX_PW}
      - API_KEY=${MATRIX_WEBHOOK_API_KEY}
    restart: always
  nginx:
    image: nginx:1.25
    ports:
      - "8000:80"
    volumes:
      - "${CLUSTER_DEPLOY_ROOT}/nginx/:/usr/share/nginx/html:ro"
    restart: always
volumes:
  prometheus-data:
networks:
  lemmy-meter:
    attachable: true
