---
modules:

  ##################################################################################################
  # http 2xx
  ##################################################################################################

  http_api_2xx:
    prober: http
    timeout: 10s
    http:
      valid_http_versions:
        - HTTP/1.1
        - HTTP/2.0
      method: GET
      valid_status_codes:
        - 200
      follow_redirects: true
      fail_if_ssl: false
      fail_if_not_ssl: true
      tls_config:
        insecure_skip_verify: false
      preferred_ip_protocol: 'ip4'
      ip_protocol_fallback: false

  http_page_2xx:
    prober: http
    timeout: 20s
    http:
      valid_http_versions:
        - HTTP/1.1
        - HTTP/2.0
      method: GET
      valid_status_codes:
        - 200
      follow_redirects: true
      fail_if_ssl: false
      fail_if_not_ssl: true
      tls_config:
        insecure_skip_verify: false
      preferred_ip_protocol: 'ip4'
      ip_protocol_fallback: false

  ##################################################################################################
  # http 4xx
  ##################################################################################################

  http_api_4xx:
    prober: http
    timeout: 10s
    http:
      valid_http_versions:
        - HTTP/1.1
        - HTTP/2.0
      method: GET
      valid_status_codes: &_http_4xx_codes
        - 400
        - 401
        - 403
        - 404
        - 405
        - 408
        - 409
      follow_redirects: true
      fail_if_ssl: false
      fail_if_not_ssl: true
      tls_config:
        insecure_skip_verify: false
      preferred_ip_protocol: 'ip4'
      ip_protocol_fallback: false

  http_page_4xx:
    prober: http
    timeout: 20s
    http:
      valid_http_versions:
        - HTTP/1.1
        - HTTP/2.0
      method: GET
      valid_status_codes: *_http_4xx_codes
      follow_redirects: true
      fail_if_ssl: false
      fail_if_not_ssl: true
      tls_config:
        insecure_skip_verify: false
      preferred_ip_protocol: 'ip4'
      ip_protocol_fallback: false

  ##################################################################################################
  # http 5xx
  ##################################################################################################

  http_api_5xx:
    prober: http
    timeout: 10s
    http:
      valid_http_versions:
        - HTTP/1.1
        - HTTP/2.0
      method: GET
      valid_status_codes: &_http_5xx_codes
        - 500
        - 501
        - 502
        - 503
        - 504
        - 505
      follow_redirects: true
      fail_if_ssl: false
      fail_if_not_ssl: true
      tls_config:
        insecure_skip_verify: false
      preferred_ip_protocol: 'ip4'
      ip_protocol_fallback: false

  http_page_5xx:
    prober: http
    timeout: 20s
    http:
      valid_http_versions:
        - HTTP/1.1
        - HTTP/2.0
      method: GET
      valid_status_codes: *_http_5xx_codes
      follow_redirects: true
      fail_if_ssl: false
      fail_if_not_ssl: true
      tls_config:
        insecure_skip_verify: false
      preferred_ip_protocol: 'ip4'
      ip_protocol_fallback: false
