---
modules:
  default:
    headers:
      X-Dummy: my-test-header
    metrics:
      - name: example_global_value
        path: "{ .counter }"
        help: Example of a top-level global value scrape in the json
        labels:
          environment: beta # static label
          location: "planet-{.location}" # dynamic label
      - name: example_timestamped_value
        type: object
        path: '{ .values[?(@.state == "INACTIVE")] }'
        epochTimestamp: "{ .timestamp }"
        help: Example of a timestamped value scrape in the json
        labels:
          environment: beta # static label
        values:
          count: "{.count}" # dynamic value
      - name: example_value
        type: object
        help: Example of sub-level value scrapes from a json
        path: '{.values[?(@.state == "ACTIVE")]}'
        labels:
          environment: beta # static label
          id: "{.id}" # dynamic label
        values:
          active: 1 # static value
          count: "{.count}" # dynamic value
          boolean: "{.some_boolean}"

  animals:
    metrics:
      - name: animal
        type: object
        help: Example of top-level lists in a separate module
        path: "{ [*] }"
        labels:
          name: "{ .noun }"
          predator: "{ .predator }"
        values:
          population: "{ .population }"
