####################################################################################################
# Copyright (c) 2023 Bahman Movaqar
#
# This file is part of lemmy-meter.
# lemmy-meter is free software: you can redistribute it and/or modify it under the terms of the GNU
# General Public License as published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version.
#
# lemmy-meter is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without
# even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
# General Public License for more details.
#
# You should have received a copy of the GNU General Public License along with lemmy-meter.
# If not, see <https://www.gnu.org/licenses/>.
####################################################################################################

---

####################################################################################################
# general
####################################################################################################

global:
  scrape_interval: 10s

####################################################################################################
# jobs
####################################################################################################

scrape_configs:

  ##################################################################################################
  # api_getPosts

  - job_name: api_getPosts
    scrape_interval: 20s
    metrics_path: /probe
    params:
      module: &http_api_modules
        - http_api_2xx
        - http_api_4xx
        - http_api_5xx
    static_configs:
      - targets: &lemmy_instances
        - enterprise.lemmy.ml
        - ds9.lemmy.ml
        - voyager.lemmy.ml
    relabel_configs:
      - source_labels: [__address__]
        target_label: lemmy_instance
        replacement: $1
      - source_labels: [__address__]
        target_label: __param_target
        replacement: https://$1/api/v3/post/list?limit=1
      - target_label: __address__
        replacement: blackbox_exporter:9115
      - source_labels: [__param_module]
        target_label: probe

  ##################################################################################################
  # api_getComments

  - job_name: api_getComments
    scrape_interval: 20s
    metrics_path: /probe
    params:
      module: *http_api_modules
    static_configs:
      - targets: *lemmy_instances
    relabel_configs:
      - source_labels: [__address__]
        target_label: lemmy_instance
        replacement: $1
      - source_labels: [__address__]
        target_label: __param_target
        replacement: https://$1/api/v3/comment/list?limit=1
      - target_label: __address__
        replacement: blackbox_exporter:9115
      - source_labels: [__param_module]
        target_label: probe


  ##################################################################################################
  # api_getCommunities

  - job_name: api_getCommunities
    scrape_interval: 20s
    metrics_path: /probe
    params:
      module: *http_api_modules
    static_configs:
      - targets: *lemmy_instances
    relabel_configs:
      - source_labels: [__address__]
        target_label: lemmy_instance
        replacement: $1
      - source_labels: [__address__]
        target_label: __param_target
        replacement: https://$1/api/v3/community/list?limit=1
      - target_label: __address__
        replacement: blackbox_exporter:9115
      - source_labels: [__param_module]
        target_label: probe


  ##################################################################################################
  # webpage_landing_page

  - job_name: webpage_landing_page
    scrape_interval: 30s
    metrics_path: /probe
    params:
      module:
        - http_page_2xx
        - http_page_4xx
        - http_page_5xx
    static_configs:
      - targets: *lemmy_instances
    relabel_configs:
      - source_labels: [__address__]
        target_label: lemmy_instance
        replacement: $1
      - source_labels: [__address__]
        target_label: __param_target
        replacement: https://$1/
      - target_label: __address__
        replacement: blackbox_exporter:9115
      - source_labels: [__param_module]
        target_label: probe

  ##################################################################################################
  # blackbox_exporter

  - job_name: blackbox_exporter
    metrics_path: /metrics
    static_configs:
      - targets:
        - blackbox_exporter:9115
