---
- name: Deploy lemmy-meter
  hosts: all

  tasks:
    - ansible.builtin.assert:
        that:
          - lemmy_meter_archive_path
          - lemmy_meter_command_path
          - lemmy_meter_cluster_env
          - lemmy_meter_cluster_stop

    - name: Include environment-specific variables
      when: lemmy_meter_cluster_env == 'prod'
      ansible.builtin.include_vars:
        file: "../{{ lemmy_meter_cluster_env }}-vars.vault.yml"

    - name: Ensure ~/bin exists
      ansible.builtin.file:
        path: "${HOME}/bin"
        state: directory

    - name: Copy lemmy-meter command
      ansible.builtin.copy:
        src: "{{ lemmy_meter_command_path }}"
        dest: "${HOME}/bin/lemmy-meter"
        remote_src: false
        mode: "u+x"
      register: _result
      changed_when: _result is success

    - name: Stop the cluster
      when: lemmy_meter_cluster_stop | bool
      block:
        - name: Check if there is a previous installation
          ansible.builtin.stat:
            path: "${HOME}/var"
          register: previous_instalation

        - name: Stop the cluster
          when: previous_instalation.stat.exists
          ansible.builtin.command:
            cmd: >-
              ${HOME}/bin/lemmy-meter
                cluster.env={{ lemmy_meter_cluster_env }}
                down
          register: _result
          changed_when: _result is success

    - name: Extract the archive
      ansible.builtin.unarchive:
        src: "{{ lemmy_meter_archive_path }}"
        dest: "${HOME}"
      register: _result
      changed_when: _result is success

    - name: Populate matrix-webhook parameters
      when: lemmy_meter_cluster_env == 'prod'
      block:
        - name: MATRIX_WEBHOOK_MATRIX_ID
          ansible.builtin.lineinfile:
            path: "${HOME}/var/config/{{ lemmy_meter_cluster_env }}.conf"
            regexp: "^MATRIX_WEBHOOK_MATRIX_ID="
            insertafter: EOF
            line: "MATRIX_WEBHOOK_MATRIX_ID={{ MATRIX_WEBHOOK_MATRIX_ID }}"
            create: true
            state: present

        - name: MATRIX_WEBHOOK_MATRIX_PW
          ansible.builtin.lineinfile:
            path: "${HOME}/var/config/{{ lemmy_meter_cluster_env }}.conf"
            regexp: "^MATRIX_WEBHOOK_MATRIX_PW="
            insertafter: EOF
            line: "MATRIX_WEBHOOK_MATRIX_PW={{ MATRIX_WEBHOOK_MATRIX_PW }}"
            create: true
            state: present

        - name: MATRIX_WEBHOOK_API_KEY
          ansible.builtin.lineinfile:
            path: "${HOME}/var/config/{{ lemmy_meter_cluster_env }}.conf"
            regexp: "^MATRIX_WEBHOOK_API_KEY="
            insertafter: EOF
            line: "MATRIX_WEBHOOK_API_KEY={{ MATRIX_WEBHOOK_API_KEY }}"
            create: true
            state: present

    - name: Populate smtp parameters
      when: lemmy_meter_cluster_env == 'prod'
      block:
        - name: SMTP_USER
          ansible.builtin.lineinfile:
            path: "${HOME}/var/config/{{ lemmy_meter_cluster_env }}.conf"
            regexp: "^SMTP_USER="
            insertafter: EOF
            line: "SMTP_USER={{ SMTP_USER }}"
            create: yes
            state: present

        - name: SMTP_PASSWORD
          ansible.builtin.lineinfile:
            path: "${HOME}/var/config/{{ lemmy_meter_cluster_env }}.conf"
            regexp: "^SMTP_PASSWORD="
            insertafter: EOF
            line: "SMTP_PASSWORD={{ SMTP_PASSWORD }}"
            create: yes
            state: present

    - name: Populate alertmanager config
      when: lemmy_meter_cluster_env == 'prod'
      block:
        - name: AM_CATCHALL_DISCORD_WEBHOOK
          ansible.builtin.replace:
            path: "${HOME}/var/alertmanager/alertmanager.yml"
            regexp: '\${AM_CATCHALL_DISCORD_WEBHOOK}'
            replace: "{{ AM_CATCHALL_DISCORD_WEBHOOK }}"

    - name: Start the cluster
      ansible.builtin.command:
        cmd: >-
          ${HOME}/bin/lemmy-meter cluster.env={{ lemmy_meter_cluster_env }} up
      register: _result
      changed_when: _result is success
