---
- name: Reset Grafana password
  hosts: all

  tasks:
    - ansible.builtin.assert:
        that:
          - lemmy_meter_server_app_root is defined
          - lemmy_meter_server_deploy_root is defined
          - lemmy_meter_grafana_new_password is defined

    - name: Reset Grafana password
      community.general.make:
        chdir: '{{ lemmy_meter_server_app_root }}'
        target: lemmy-meter.grafana.reset-password
        params:
          DEPLOY_ROOT: '~/var/'
          lemmy-meter.grafana.new-password: '{{ lemmy_meter_grafana_new_password }}'
      register: _result
      changed_when: _result is success
